// This file is automatically generated. Do not edit it directly.
import { createClient, type Session, type SupabaseClient } from "@supabase/supabase-js";

import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

export const supabaseConfigErrorMessage = isSupabaseConfigured
  ? null
  : "Missing frontend Supabase environment variables. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY, or enable VITE_DEMO_MODE=true for demo-only deployments.";

const createDisabledSupabaseClient = (): SupabaseClient<Database> => {
  const error = new Error(supabaseConfigErrorMessage ?? "Supabase is not configured.");

  return {
    auth: {
      getSession: async () => ({ data: { session: null as Session | null }, error }),
      onAuthStateChange: () => ({
        data: {
          subscription: {
            unsubscribe: () => undefined,
          },
        },
      }),
      signUp: async () => ({ data: { user: null, session: null }, error }),
      signInWithPassword: async () => ({ data: { user: null, session: null }, error }),
      signOut: async () => ({ error: null }),
    },
  } as unknown as SupabaseClient<Database>;
};

export const supabase = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: sessionStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createDisabledSupabaseClient();
